config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"
  get '/dashbord', to: "pages#dashbord"
  delete "dreams/:id", to: "pages#destroy", as: :destroy_dream
  # root "articles#index"
  resources :dreams, except: [:show]

  resources :dreams, only: [:show] do
    resources :reservations, only: :create
  end
  resources :reservations, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dream.rb
class Dream < ApplicationRecord
  has_many :reservations
  belongs_to :user # loueur
  has_one_attached :photo
  validates :name, presence: true
  validates :details, presence: true
  validates :photo, presence: true
  validates :price, presence: true
  validates :content, presence: true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :dream
  belongs_to :user
  validates :date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reservations
  has_many :dreams
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/dreams_controller.rb
class DreamsController < ApplicationController
  before_action :set_dream, only: [:show, :edit, :update]

  def index
    @dreams = Dream.all
      if params[:query].present?
        sql_query = "name ILIKE :query OR details ILIKE :query OR content ILIKE :query"
        @dreams = Dream.where(sql_query, query: "%#{params[:query]}%")
      else
        @dreams = Dream.all
      end
  end

  def show
    @reservation = Reservation.new
  end

  def new
    @dream = Dream.new
  end

  def create
    @dream = Dream.new(dream_params)
    @dream.user_id = current_user.id
    if @dream.save
      redirect_to @dream, notice: 'Ton rêve a été soumis avec succès !'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @dream.update(dream_params)

    redirect_to dream_path(@dream)
  end

  private

  def dream_params
    params.require(:dream).permit(:name, :details, :content, :price, :photo)
  end

  def set_dream
    @dream = Dream.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end

  def dashbord
    @dreams = Dream.all
    @reservations = Reservation.all
  end

  def destroy
    @dream = Dream.find(params[:id])
    @dream.destroy

    redirect_to dashbord_path, status: :see_other
  end


end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def create
    @dream = Dream.find(params[:dream_id])
    @reservation = Reservation.new(reservation_params)
    @reservation.dream = @dream
    @reservation.user_id = current_user.id

    if @reservation.save
      redirect_to dashbord_path, notice: 'Réservation validée !'
    else
      redirect_to dreams_path, notice: 'Réservation annulée !'
      # render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy

    redirect_to dashbord_path, status: :see_other
  end

  private

  def reservation_params
    params.require(:reservation).permit(:date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dreams/edit.html.erb
<div class='form'>
  <div class='box-container' style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url(https://res.cloudinary.com/dsef2i7mv/image/upload/v1669148676/fond-pastel-couleur-abstraite-ciel-doux-fond-nuage-couleur-pastel_6529-2_ledfr4.webp)">
    <div class="row justify-content-center">
      <div class="col-12 col-sm-4" class='bloc'>
        <h1 class='title'><b>Je modifie mon rêve</b></h1>
          <div>
            <%= simple_form_for @dream do |f| %>
              <div class='name-price'>
              <div class='one'>
              <%= f.input :name, label: 'Nom du rêve', placeholder: 'Rêve romantique' %>
              </div>
              <div class='photo-details'>
              <%= f.input :details, label: 'Résumé du rêve', placeholder: "Un rêve à l'eau de rose" %>
              </div>
              <div>
              <%= f.input :content, label: 'Description détaillée', placeholder: 'Décrivez votre rêve dans les détails...' %>
              </div>
              </div>
              <div class='two'>
              <%= f.input :price, label: 'Prix du rêve (€)', placeholder: '100' %>
              </div>
              <div class='photo-details'>
              <%= f.input :photo, as: :file %>
              </div>
              <%= f.submit 'Je confirme les modifications', class:"btn btn-danger edit-btn"%>
            <% end %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/dreams/index.html.erb
<div class="search-position">
<div class="index-search"><%= form_with url: dreams_path, method: :get, class: "d-flex" do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Rêve par mot-clé"
  %>
  <%= submit_tag "Chercher", class: "btn btn-primary search-btn" %>
<% end %>
</div>
</div>
<div class='container index'>
  <h2><b>Choisissez ici le rêve de vos rêves...</b></h2>

  <div class="cards-container index-cards-container">
    <% @dreams.each do |dream| %>
      <div class="card card-index" style="width: 18rem;">
        <div class="image-container image-container-index">
          <%= cl_image_tag dream.photo.key, crop: :fill, class:'image-card image-card-index' %>
        </div>
        <div class="card-body">
          <div class="card-name-price card-name-price-index">
            <h5 class="card-title"><%=dream.name%></h5>
            <h5 class="card-title price"><%=dream.price%>€</h5>
          </div>
          <p class="card-text"><%=dream.details%></p>
          <%= link_to 'Découvrez ce rêve', dream_path(dream), class:"btn-flat index-btn" %>
        </div>
      </div>
      <%end%>
  </div>
</div>

app/views/dreams/new.html.erb
<div class='form'>
  <div class='box-container' style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url(https://res.cloudinary.com/dsef2i7mv/image/upload/v1669148676/fond-pastel-couleur-abstraite-ciel-doux-fond-nuage-couleur-pastel_6529-2_ledfr4.webp)">
    <div class="row justify-content-center">
      <div class="col-12 col-sm-4" class='bloc'>
        <h1 class='title'><b>Je crée mon rêve</b></h1>
          <div>
            <%= simple_form_for @dream do |f| %>
              <div class='name-price'>
              <div class='one'>
              <%= f.input :name, label: 'Nom du rêve', placeholder: 'Rêve romantique' %>
              </div>
              <div class='photo-details'>
              <%= f.input :details, label: 'Résumé du rêve', placeholder: "Un rêve à l'eau de rose" %>
              </div>
              <div>
              <%= f.input :content, label: 'Description détaillée', placeholder: 'Décrivez votre rêve dans les détails...' %>
              </div>
              </div>
              <div class='two'>
              <%= f.input :price, label: 'Prix du rêve (€)', placeholder: '100' %>
              </div>
              <div class='photo-details'>
              <%= f.input :photo, as: :file %>
              </div>
              <%= f.submit 'Je confirme mon rêve', class:"btn btn-danger create-btn"%>
            <% end %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/dreams/show.html.erb
<div class="show-container">

  <div class= "show-h2">
    <h2><b><%= @dream.name %></b></h2>
  </div>

  <div class="show-bloc">
    <div class= "show-img">
      <%= cl_image_tag @dream.photo.key , crop: :fill , height: 400 , width: 700 %>
    </div>
    <div class= "show-infos">
      <h5><b><%= @dream.details %> ! </b></h5><br>
      <p class='show-price'><%= @dream.price %> € </p>
      <p class='card-title'> <%= @dream.content %> </p> <br>

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary show-btn-popup" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Réservez
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content" style="background-color: white">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Je réserve mon rêve</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      <!-- Contenu de mon formulaire -->
        <div class='form'>
          <div class="row justify-content-center">
            <div class="col-12 col-sm-4" class='bloc'>
                <div>
                  <%= simple_form_for [@dream, @reservation] do |f| %>
                    <h3 class='resa-dream-name'><%= @dream.name %></h3>
                    <br>
                    <%= cl_image_tag @dream.photo.key , crop: :fill , height: 400 , width: 700 %>
                    <br>
                    <br>
                    <div class='details-price-resa'>
                    <br>
                    <b><%= @dream.details %> !</b>
                    <p class='resa-price'><%= @dream.price %> € </p>
                    </div>
                    <div class='show-date'>
                    <%= f.input :date, use_month_names: ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'], label: 'Quand souhaitez-vous rêver?' %>
                    </div>
                    <div class="modal-footer">
                    <%= submit_tag 'Je confirme ma réservation', class:"btn btn-danger resa-btn"%>
                    <%# <button type="button" class="btn btn-primary">Save changes</button> %>
                  </div>
                  <% end %>
                </div>
            </div>
        </div>
      <!-- Fin du contenu formulaire -->
      </div>
    </div>
  </div>
</div>

      <%# <%= link_to 'Réservez!', new_dream_reservation_path(@dream), class:'btn btn-flat' %> %>
    </div>
      <a class="btn btn-ghost" href="/dreams">Retour</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dreamscatcher</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>

    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "devise/shared/flashes" %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/dashbord.html.erb
<h2><b>Mes rêves en location</b></h2>
<%# si connecté, affiche les dreams créés %>


<div class="container container-dashbord-create">
  <% @dreams.each do |dream|%>
    <% if dream.user == current_user %>
      <div class="card card-dashbord-create">
          <%if dream.photo.key%>
            <%= cl_image_tag dream.photo.key, crop: :fill, class:"card-img card-img-dashbord" %>
          <%end%>
        <div class="card-img-overlay name-price-dashbord">
            <h5 class="card-title"><%=dream.name%></h5>
            <h5 class="card-title"><%=dream.price%>€</h5>
        </div>
          <%= link_to "Modifier", edit_dream_path(dream), class:"btn-flat dashbord-btn-edit"%>
          <%= link_to "Supprimer", destroy_dream_path(dream), data: {turbo_method: :delete, turbo_confirm: "Êtes-vous sûr·e ?"}, class:"btn-flat dashbord-btn"%>
      </div>
    <%end%>
  <%end%>
</div>
<div class='d-flex justify-content-center mt-5'>
  <%= link_to "☁️ Ajouter un rêve", new_dream_path, class:"btn-flat dashbord-btn-add"%>
</div>


<h2 class='m-5'><b>Mes réservations</b></h2>
  <%if current_user.reservations.blank? %>
    <div class="d-flex justify-content-center text-sans-resa">
      <h5 class="card-title p-4 mb-4">Vous n'avez pas encore de réservation... 🌈</h5>
    </div>
  <%else%>
    <div class="container container-dashbord-res">
      <% @reservations.each do |reservation|%>
        <div class="card mb-3 card-dashbord-res" style="max-width: 540px;">
          <% if reservation.user == current_user %>
            <div class="row g-0">
              <div class="col-md-4">
                <%= cl_image_tag reservation.dream.photo.key, crop: :fill, class:"card-img card-img-dashbord-two" %>
              </div>
              <div class="col-md-8">
                <div class="card-body card-body-dashbord">
                  <h5 class="card-title"><%=reservation.dream.name %></h5>
                  <p class="card-title"><%=reservation.dream.details %></p>
                  <h6 class="card-title"><%=reservation.date%></h6>
                  <%= link_to "Annuler la réservation", reservation_path(reservation), data: {turbo_method: :delete, turbo_confirm: "Êtes-vous sûr·e ?"}, class:"btn-flat dashbord-btn"%>
                </div>
              </div>
            </div>
          <%end%>
        </div>
      <%end%>
    </div>
  <%end%>

<div class='d-flex justify-content-center mt-5'>
  <%= link_to "☁️ Réservez un rêve", dreams_path, class:"btn-flat dashbord-btn-add mb-4"%>
</div>

app/views/pages/home.html.erb
<div class="headers">
  <h2><b>Choisir son rêve? C'est maintenant possible grâce à Dreamscatcher !</b></h2>
</div>

<div class="content" >
  <div class="content-homepage">
    <p>Nous savons que les rêves sont un moyen pour l'inconscient de traiter des informations qu'il a vu dans la journée.  </p>
    <p>Ce processus est très important.
    <p>Mais au delà de cela, ne serait-il pas agréable d'orienter complétement son rêve afin de se réveiller en pleine forme pour la journée ?</p>
    <p class="text-présentation"><b>Avec Dreamscatcher, vous pouvez louer le rêve de votre choix.</b></p>
  </div>
</div>

<div class="flex-container">

  <div class="flex-child magenta">
    <h2><b>Réservez un rêve</b></h2>
    <p>Choisissez parmi les rêves mis en location ! Que vous ayez envie de réconfort, de frisson, de science-fiction ou de passion, vous trouverez le rêve qui correspond à vos envies !</p>
    <a class="btn btn-flat" href="/dreams">Découvrez tous les rêves</a>
  </div>

  <div class="flex-child green">
    <h2><b>Louez votre rêve</b></h2>
    <p>Vous avez une imagination débordante et une envie de partager votre rêve avec le monde ? <br>N'hésitez pas à mettre votre rêve en location.</p>
    <br>
    <a class="btn btn-flat" href="/dreams/new">Louez votre rêve</a>
  </div>
</div>

app/views/reservations/new.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'new') %>");
$("#modal-window").modal();

app/views/shared/_footer.html.erb
<div id="footer">
      <p>Retrouvez-nous sur les réseaux sociaux</p>
    <ul>
  <li><a href="#"><i class="fab fa-youtube"></i></a></li>
  <li><a href="#"><i class="fab fa-facebook"></i></a></li>
  <li><a href="#"><i class="fab fa-twitter"></i></a></li>
    </ul>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" style= "background: rgb(242,217,252);
background: linear-gradient(259deg, rgba(242,217,252,1) 0%, rgba(255,249,214,1) 100%)" >
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%=image_tag "nuage_stars.png", alt:"nuage"%>
    <% end %>
    <div class="title"><h1><b>DREAMSCATCHER</b></h1></div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <%# <li class="nav-item active">
            <%= link_to "Home", "/", class: "nav-link" %>
          <%# </li> %>
          <li class="nav-item">
            <%= link_to "Réservez un rêve", "/dreams", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Louez votre rêve", "/dreams/new", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "nuage.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Tableau de bord", dashbord_path, class: "dropdown-item" %>
              <%# <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Se déconnecter", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Se connecter", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>